domain_path: /home/knutjb/Vivado/sw_car/new_car/export/new_car/sw/standalone_ps7_cortexa9_0
app_src_dir: /home/knutjb/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
